// import type { Metadata } from "next";
import "./globals.css";

// * components
import Protected from "./(protected)/Layout";
import AppLayout from "./components/layout/Layout";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <Protected>
                    <AppLayout>{children}</AppLayout>
                </Protected>
            </body>
        </html>
    );
}
